spring:
  application:
    name: customer-portal
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:customer_portal;DB_CLOSE_DELAY=-1;MODE=PostgreSQL}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: "${SPRING_DATASOURCE_PASSWORD:}"
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  error:
    include-message: never
    include-stacktrace: never
